# config/packages/messenger.yaml

# framework:
#     messenger:
#         transports:
#             async: '%env(MESSENGER_TRANSPORT_DSN)%'
#         routing:
#             'App\Message\Notification': async

framework:
    messenger:
        buses:
            websocket_messages: ~
