controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


# config/routes.yaml
custom_404_page:
    path: /404
    controller: App\Controller\CustomErrorController::show404


return_page:
    path: '/return'
    controller: App\Controller\HomeController::pagePrecedente